### ISSUE TITLE
get cost of resources by tags

### ISSUE THREAD

**Issue by zaro0508** [toyama0919/awscost#16]
I would like to get the cost of all resources in my account that contain a specific tag or set of tags.  is this possible with this tool?

**Comment by toyama0919** [comment]
@zaro0508 
I'm sorry to reply late!
You can do it like this.

```
$ awscost --filter '{"Tags": { "Key": "tag_key", "Values": ["value"] } }'
```

See here for filter syntax.
https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_Expression.html

**Comment by zaro0508** [comment]
thank you!
