### ISSUE TITLE
some errors 

### ISSUE THREAD

**Issue by lichengshuang** [toyama0919/awscost#19]
hi,  when run reame.md example, find follow errors. 
awscost -t  , can output  json or csv,  i want  aws bill data use pandas , get report on dango or Excel.

  File "1.py", line 9, in <module>
    cost_explorer = CostExplorer(
  File "/usr/local/lib/python3.8/dist-packages/awscost/cost_explorer.py", line 50, in __init__
    start or profile.get("start") or DateUtil.get_start(self.granularity, point)
  File "/usr/local/lib/python3.8/dist-packages/awscost/date_util.py", line 16, in get_start
    start_datetime = datetime.today() - timedelta(days=days)
UnboundLocalError: local variable 'days' referenced before assignment

cat 1.py 
from awscost.cost_explorer import CostExplorer
from dateutil.relativedelta import relativedelta
from datetime import datetime

start = (datetime.today() - relativedelta(months=3)).strftime("%Y-%m-01")
end = datetime.today().strftime("%Y-%m-01")

cost_explorer = CostExplorer(
    "MONTHLY", start, end, dimensions=["SERVICE"], metrics="UnblendedCost"
).get_cost_and_usage_total_and_group_by()

**Comment by Nuxij** [comment]
I got round these issues by editing `site-packages\awscost\date_util.py` and assigning `days = 0` just before the granularity check, so it looks like this:
```python
class DateUtil:
    @staticmethod
    def get_start(granularity, point):
        """
        datapointのscaleをmonth, week, dayで自動調節する
        """
        days = 0
        if granularity == "MONTHLY":
            days = 30 * point
        elif granularity == "DAILY":
            days = point

        start_datetime = datetime.today() - timedelta(days=days)
        if granularity == "MONTHLY":
            start_datetime = start_datetime.replace(day=1)
        return start_datetime.strftime("%Y-%m-%d")
```

**Comment by Nuxij** [comment]
Had to change the parameters for CostExplorer too:
```python
from awscost.cost_explorer import CostExplorer
from dateutil.relativedelta import relativedelta
from datetime import datetime
from pprint import pprint

start = (datetime.today() - relativedelta(days=7)).strftime('%Y-%m-%d')
end = (datetime.today() - relativedelta(days=0)).strftime('%Y-%m-%d')

cost_explorer = CostExplorer( None, None,
    "DAILY", 7, start, end, dimensions=["SERVICE"], metrics="UnblendedCost"
).get_cost_and_usage_total_and_group_by()

pprint(cost_explorer)
```

**Comment by alexlance** [comment]
The error goes away for me if I use named parameters:

    lines = CostExplorer(
        start=start, end=end, granularity="DAILY", dimensions=["LINKED_ACCOUNT", "SERVICE"], metrics="UnblendedCost"
    ).get_cost_and_usage_total_and_group_by()

**Comment by toyama0919** [comment]
@alexlance 
完璧な回答です！
READMEを修正しました！

https://github.com/toyama0919/awscost/pull/24
