### ISSUE TITLE
Filter out zero rows

### ISSUE THREAD

**Issue by iainelder** [toyama0919/awscost#21]
Thanks for this. It's a convenient way to tabulate costs!

Is there an option to omit the rows for which the cost is always zero (`0`)?

Filtering the output programmatically would be awkward and make this a lot less convenient, so I'm just delete such lines by hand for now.

**Comment by iainelder** [comment]
Thank you! This looks useful. I will try it when you make the new release.

awscost is always in my toolbox for cost management tasks.

**Comment by toyama0919** [comment]
released.
https://pypi.org/project/awscost/
