### ISSUE TITLE
How to get cost group by the TAG type ?

### ISSUE THREAD

**Issue by kashishtrivedi** [toyama0919/awscost#27]
https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetCostAndUsage.html#API_GetCostAndUsage_RequestSyntax

See section : GroupBy

"When you group by the TAG type and include a valid tag key, you get all tag values, including empty strings."

**Comment by toyama0919** [comment]
Thanks for the report.
Can't do it now, but will support it.

**Comment by toyama0919** [comment]
Already released.

See below
https://github.com/toyama0919/awscost?tab=readme-ov-file#group-by-tag

(This cannot be achieved on the command line, but can be done using a config file.
